#include "obj_exporter.h"
#include <fstream>
#include <iostream>
#include <cstdio>

static void writeMesh(std::ofstream& out, const ObjMesh& mesh,
                      const std::string& groupName) {
    if (mesh.vertices.empty()) return;

    if (!groupName.empty())
        out << "g " << groupName << "\n";

    for (const auto& v : mesh.vertices)
        out << "v " << v.x << " " << v.y << " " << v.z << "\n";
    for (const auto& vt : mesh.texcoords)
        out << "vt " << vt.x << " " << vt.y << "\n";
    for (const auto& vn : mesh.normals)
        out << "vn " << vn.x << " " << vn.y << " " << vn.z << "\n";

    for (const auto& f : mesh.faces) {
        out << "f";
        for (int i = 0; i < 3; ++i) {
            out << " " << f.v[i];
            if (f.vt[i] > 0 || f.vn[i] > 0) {
                out << "/";
                if (f.vt[i] > 0) out << f.vt[i];
                if (f.vn[i] > 0) out << "/" << f.vn[i];
            }
        }
        out << "\n";
    }
}

bool ObjExporter::write(const std::string& filepath, const ObjMesh& mesh,
                        const std::string& mtlName) {
    std::ofstream out(filepath);
    if (!out) {
        std::cerr << "ERROR: Cannot write " << filepath << std::endl;
        return false;
    }

    out << "# Generated by CourtModelGenerator\n";
    if (!mtlName.empty())
        out << "mtllib " << mtlName << "\n";

    writeMesh(out, mesh, "court_model");
    out.close();
    std::cout << "  -> Wrote " << filepath << std::endl;
    return true;
}

bool ObjExporter::writeGroups(const std::string& filepath,
                               const std::vector<Group>& groups,
                               const std::string& mtlName) {
    std::ofstream out(filepath);
    if (!out) {
        std::cerr << "ERROR: Cannot write " << filepath << std::endl;
        return false;
    }

    out << "# Generated by CourtModelGenerator\n";
    if (!mtlName.empty())
        out << "mtllib " << mtlName << "\n";

    // Track vertex/texcoord/normal index offsets per group
    int voff = 0, vtoff = 0, vnoff = 0;

    for (const auto& g : groups) {
        if (g.mesh.vertices.empty()) continue;

        if (!g.name.empty())
            out << "g " << g.name << "\n";

        for (const auto& v : g.mesh.vertices)
            out << "v " << v.x << " " << v.y << " " << v.z << "\n";
        for (const auto& vt : g.mesh.texcoords)
            out << "vt " << vt.x << " " << vt.y << "\n";
        for (const auto& vn : g.mesh.normals)
            out << "vn " << vn.x << " " << vn.y << " " << vn.z << "\n";

        for (const auto& f : g.mesh.faces) {
            out << "f";
            for (int i = 0; i < 3; ++i) {
                int idx = f.v[i] > 0 ? f.v[i] + voff : f.v[i];
                out << " " << idx;
                if (f.vt[i] > 0 || f.vn[i] > 0) {
                    out << "/";
                    if (f.vt[i] > 0) out << (f.vt[i] + vtoff);
                    if (f.vn[i] > 0) out << "/" << (f.vn[i] + vnoff);
                }
            }
            out << "\n";
        }

        voff += (int)g.mesh.vertices.size();
        vtoff += (int)g.mesh.texcoords.size();
        vnoff += (int)g.mesh.normals.size();
    }

    out.close();
    std::cout << "  -> Wrote " << filepath << std::endl;
    return true;
}

bool ObjExporter::writeMtl(const std::string& filepath,
                            const glm::vec3& diffuse,
                            float opacity,
                            const std::string& textureName) {
    std::ofstream out(filepath);
    if (!out) {
        std::cerr << "ERROR: Cannot write " << filepath << std::endl;
        return false;
    }

    out << "# Material file generated by CourtModelGenerator\n";
    out << "newmtl court_material\n";
    out << "Ka 0.2 0.2 0.2\n";
    out << "Kd " << diffuse.r << " " << diffuse.g << " " << diffuse.b << "\n";
    out << "Ks 0.1 0.1 0.1\n";
    out << "Ns 10.0\n";
    if (opacity < 1.0f)
        out << "d " << opacity << "\n";
    if (!textureName.empty())
        out << "map_Kd " << textureName << "\n";

    out.close();
    std::cout << "  -> Wrote " << filepath << std::endl;
    return true;
}
